/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#a04223",
        "primary-dim": "#903618",
        "primary-container": "#ffad94",
        "on-primary": "#fff7f5",
        "on-primary-container": "#712003",
        "secondary": "#006b64",
        "secondary-dim": "#005e57",
        "secondary-container": "#8ef4e9",
        "on-secondary": "#e2fffa",
        "on-secondary-container": "#005c56",
        "tertiary": "#7a5a00",
        "tertiary-container": "#fec330",
        "on-tertiary": "#fff8f1",
        "on-tertiary-container": "#584000",
        "error": "#ac3434",
        "error-container": "#f56965",
        "on-error": "#fff7f6",
        "surface": "#fff8f1",
        "surface-dim": "#e6d9bf",
        "surface-bright": "#fff8f1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fdf2e2",
        "surface-container": "#f8edda",
        "surface-container-high": "#f3e7d2",
        "surface-container-highest": "#eee1ca",
        "on-surface": "#393222",
        "on-surface-variant": "#675e4c",
        "outline": "#837a66",
        "outline-variant": "#bcb19b",
        "background": "#fff8f1",
        "on-background": "#393222",
        "inverse-surface": "#110e06",
        "inverse-on-surface": "#a49c8f",
        "inverse-primary": "#fd8863",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Be Vietnam Pro", "sans-serif"],
      },
    },
  },
  plugins: [],
}
